# Generated by Django 5.0.3 on 2024-04-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_level', models.IntegerField(max_length=1)),
                ('recommend', models.TextField()),
            ],
        ),
    ]
