# Generated by Django 5.0.3 on 2024-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0002_alter_recommendation_stress_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('branch', models.CharField(max_length=100)),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(max_length=100)),
            ],
        ),
    ]
