# Generated by Django 5.0.3 on 2024-04-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stressapp', '0004_student_password_student_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
